## You should change each of the following fields
## to customize your blog

title: Stat 386 Blog
description: "My thoughts and experiences with various statistical projects" 
author: Talmage Anderson
author_description: "Current BYU Applied Statistics & Analytics Major" 

url: https://t-anderson21.github.io ## change this to https://yourusername.github.io
baseurl: /blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  t-anderson21
    twitter: 
    facebook: 
    email: 
    linkedin: talmage-anderson17
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




